[package]
name = "invoy"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.36", features = ["derive"] }
lopdf = "0.36.0"
pdf = "0.9.0"
regex = "1.11.1"
regex-macro = "0.3.0"
thiserror = "2.0.12"
windows-sys = "0.59.0"
